POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "userId":"test",
    "password":"test"
}

POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "userId":"admin",
    "password":"admin"
    
}


GET http://localhost:8080/reviews/66499585be116d4a22e07b6f/comments
POST http://localhost:8080/reviews/rate
Content-Type: application/json

{
  "novelId": "66499585be116d4a22e07b6f",
  "userId":"test",
  "rating": 5
}
